# Generated by Django 3.2.7 on 2021-09-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=400)),
                ('photo', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Sports', 'Sports'), ('Home', 'Home'), ('Food', 'Food'), ('Books', 'Books')], max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
